# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`Macro-Simple`
	:runtime-requirement    [ :on "perl 5.008003"^^:CpanId ];
	:test-requirement       [ :on "Test::More 0.96"^^:CpanId ];
	:develop-recommendation [ :on "Dist::Inkt 0.001"^^:CpanId ];
	.

